#!/usr/bin/env bash
#    ____         __       ____               __     __
#   /  _/__  ___ / /____ _/ / / __ _____  ___/ /__ _/ /____ ___
#  _/ // _ \(_-</ __/ _ `/ / / / // / _ \/ _  / _ `/ __/ -_|_-<
# /___/_//_/___/\__/\_,_/_/_/  \_,_/ .__/\_,_/\_,_/\__/\__/___/
#                                 /_/
#

# Check if command exists
_checkCommandExists() {
    command -v "$1" &> /dev/null
}

_isInstalled() {
    package="$1"
    check="$($aur_helper -Qs --color always "${package}" | grep "local" | grep "${package} ")"
    if [ -n "${check}" ]; then
        echo 0
        return
    fi
    echo 1
    return
}

# ------------------------------------------------------
# Confirm Start
# ------------------------------------------------------

sleep 1
clear
figlet -f smslant "Updates"
echo
primarycolor=$(cat ~/.config/dotfiles/colors/primary)
onsurfacecolor=$(cat ~/.config/dotfiles/colors/onsurface)
onprimarycolor=$(cat ~/.config/dotfiles/colors/onprimary)
if gum confirm --selected.background=$primarycolor --selected.foreground=$onprimarycolor --prompt.foreground=$onsurfacecolor "DO YOU WANT TO START THE UPDATE NOW?"; then
    echo
    echo ":: Update started..."
elif [ $? -eq 130 ]; then
    exit 130
else
    echo
    echo ":: Update canceled."
    exit
fi

# ----------------------------------------------------- 
# Install update
# ----------------------------------------------------- 

yay_installed="false"
paru_installed="false"
if _checkCommandExists "yay"; then
    yay_installed="true"
fi
if _checkCommandExists "paru"; then
    paru_installed="true"
fi
if [[ $yay_installed == "true" ]] && [[ $paru_installed == "false" ]]; then
    yay
elif [[ $yay_installed == "false" ]] && [[ $paru_installed == "true" ]]; then
    paru -Syu --noconfirm
else
    yay
fi
echo

# Flatpak
echo ":: Searching for Flatpak updates..."
flatpak update
echo

# Refresh Quickshell Statusbar
qs ipc call updates refresh
# qs ipc call updates reset

# Finishing
echo ":: Update complete! Press [ENTER] to close."
read
