#!/usr/bin/env bash

info() { echo -e "${BLUE}[BOOTSTRAP]${NC} $1"; }
success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
error() { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# --- 2. OS DETECTION (By Package Manager) ---

INSTALL_CMD="sudo pacman -S --noconfirm nvidia-open-dkms nvidia-utils nvidia-settings egl-wayland lib32-nvidia-utils"

echo
warn "The script will install the NVIDIA graphics drivers on your system."
if gum confirm "Do you want to proceed?"; then
    bash -c "$INSTALL_CMD"
    echo 'source = ~/.config/hypr/conf/environments/nvidia.conf' > $HOME/.config/hypr/conf/environment.conf
    success "Done!"
fi
