#!/usr/bin/env bash
WALLPAPER_APP="quickshell"

if [ -f $HOME/.config/dotfiles/settings/wallpaper-folder ]; then
    RAW_FOLDER=$(cat $HOME/.config/dotfiles/settings/wallpaper-folder)
    WALLPAPER_FOLDER="${RAW_FOLDER//\$HOME/$HOME}"
    WALLPAPER_FOLDER="${WALLPAPER_FOLDER//\~/$HOME}"
fi

if [ "$1" == "--random" ]; then
    $HOME/.config/dotfiles/scripts/wallpaper --random
    exit
fi

qs -p ~/.config/quickshell/wallpaper-picker.qml &
