import "./overlay"
import "./widgets"
import "./services"
import "./theme"
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland

ShellRoot {
    id: root

    property string overlayView: "island" // "island", "movies", "wallpaper"

    // Re-apply the last wallpaper (and its Matugen theme) on login/reboot.
    Component.onCompleted: {
        Quickshell.execDetached([Quickshell.shellPath("scripts/restore_wallpaper.sh")])
    }

    // ---------------------------------------------------------------
    // Live color updates. Two sources feed the Theme singleton so the island
    // always matches the current wallpaper:
    //   1. theme/colors.json        — flat palette written by matugen's
    //      quickshell_theme template (config.toml). Generated by the quickshell
    //      wallpaper pipeline (scripts/wallpaper.sh) AND by the system
    //      wallpaper pipeline now that it runs matugen with config.toml.
    //   2. ~/.cache/matugen/colors.json — matugen's canonical nested output.
    //      Any matugen run that does NOT use config.toml (e.g. a manual
    //      `matugen image …`) only writes here, so watching it keeps the shell
    //      in sync no matter which pipeline set the wallpaper.
    // ---------------------------------------------------------------

    function parseColors(t) {
        t = (t || "").trim()
        if (t.length < 10) return null
        try { return JSON.parse(t) } catch (e) {
            console.error("theme colors parse error:", e)
            return null
        }
    }

    function applyThemeColors(obj) {
        if (!obj) return
        var batch = {}
        if (obj.background)       batch.background       = obj.background
        if (obj.surface)          batch.surface          = obj.surface
        if (obj.surfaceBright)    batch.surfaceBright    = obj.surfaceBright
        if (obj.surfaceDim)       batch.surfaceDim       = obj.surfaceDim
        if (obj.surfaceContainer) batch.surfaceContainer = obj.surfaceContainer
        if (obj.surfaceVariant)   batch.surfaceVariant   = obj.surfaceVariant
        if (obj.primary)          batch.primary          = obj.primary
        if (obj.primaryFg)        batch.primaryFg        = obj.primaryFg
        if (obj.secondary)        batch.secondary        = obj.secondary
        if (obj.tertiary)         batch.tertiary         = obj.tertiary
        if (obj.backgroundFg)     batch.backgroundFg     = obj.backgroundFg
        if (obj.surfaceFg)        batch.surfaceFg        = obj.surfaceFg
        if (obj.surfaceVariantFg) batch.surfaceVariantFg = obj.surfaceVariantFg
        if (obj.outline)          batch.outline          = obj.outline
        if (obj.outlineVariant)   batch.outlineVariant   = obj.outlineVariant
        if (obj.error)            batch.error            = obj.error
        for (var k in batch) Theme[k] = batch[k]
    }

    FileView {
        id: themeFileWatcher
        path: Quickshell.shellPath("theme/colors.json")
        watchChanges: true
        onLoaded: applyThemeColors(parseColors(text()))
        onTextChanged: applyThemeColors(parseColors(text()))
        Component.onCompleted: applyThemeColors(parseColors(text()))
    }

    // Full-screen PanelWindow — like quickshellinspire, never resizes.
    // Island mode:  masked to island area, exclusive zone
    // Widget mode:  bounding box clips to widget, click-outside closes
    PanelWindow {
        id: mainWindow

        anchors { top: true; left: true; right: true }
        implicitHeight: Screen.height

        color: "transparent"
        WlrLayershell.namespace: "qs-shell"
        WlrLayershell.layer: WlrLayer.Overlay
        // Constant exclusive zone: toggling it between island/widget modes
        // made every other window reflow (shift) when a panel opened. Keeping
        // it fixed at the island height reserves the top bar without shifting
        // anything when movie/wallpaper open.
        WlrLayershell.exclusiveZone: 46
        WlrLayershell.keyboardFocus: root.overlayView === "island" ? WlrKeyboardFocus.None : WlrKeyboardFocus.Exclusive

        focusable: true

        // ---------------------------------------------------------------
        // Mask — restrict input to the island only when the island is idle.
        // Whenever the island has an open overlay OR a widget panel (movie /
        // wallpaper) is open we use the full-window mask so every part of the
        // panel is clickable.
        //
        // IMPORTANT: always assign a real Region. Returning `undefined` here
        // left the input region stuck on the tiny island-sized mask, which is
        // exactly why the movie / wallpaper panels were impossible to click.
        // `fullWindow` is a dedicated always-visible item so the full mask is
        // never empty even while the island itself is hidden.
        // ---------------------------------------------------------------
        Item { id: fullWindow; anchors.fill: parent; visible: true }

        Region {
            id: fullMask
            Region { item: fullWindow }
        }

        Region {
            id: islandMask
            Region { item: overlayRoot.island }
        }

        mask: (root.overlayView === "island" && !overlayRoot.anyActive) ? islandMask : fullMask

        // ---------------------------------------------------------------
        // Island content — kept visible at all times (including while a
        // movie / wallpaper panel is open) so the bar doesn't vanish.
        // ---------------------------------------------------------------
        OverlayRoot {
            id: overlayRoot
            anchors.fill: parent
            visible: true
        }

        // ---------------------------------------------------------------
        // Widget bounding box — like quickshellinspire's animated Item
        // Positions and clips to the widget's layout dimensions
        // ---------------------------------------------------------------
        Item {
            id: widgetBox
            visible: root.overlayView !== "island"
            focus: true

            // Layout dimensions per widget — matching quickshellinspire WindowRegistry.js
            readonly property bool isMovie: root.overlayView === "movies" || root.overlayView === "wallpaper"
            readonly property int boxW: isMovie ? 1370 : Screen.width
            readonly property int boxH: isMovie ? 850 : 650
            readonly property int boxX: isMovie ? Math.floor((Screen.width / 2) - (boxW / 2)) : 0
            readonly property int boxY: isMovie ? Screen.height - boxH : Math.floor((Screen.height / 2) - (boxH / 2))

            x: boxX
            y: boxY
            width: boxW
            height: boxH
            clip: true

            Behavior on x { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }
            Behavior on y { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }
            Behavior on width { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }
            Behavior on height { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }

            opacity: widgetBox.visible ? 1.0 : 0.0
            Behavior on opacity {
                NumberAnimation { duration: 160; easing.type: widgetBox.visible ? Easing.OutCubic : Easing.InCubic }
            }

            Loader {
                id: movieLoader
                anchors.fill: parent
                active: root.overlayView === "movies"
                source: "movies/MovieWidget.qml"
                visible: active
                focus: active
            }

            Loader {
                id: wallpaperLoader
                anchors.fill: parent
                active: root.overlayView === "wallpaper"
                source: "wallpaper/WallpaperWidget.qml"
                visible: active
                focus: active
            }
        }

        // ---------------------------------------------------------------
        // Click-outside-to-close — full-screen MouseArea, like quickshellinspire
        // ---------------------------------------------------------------
        MouseArea {
            anchors.fill: parent
            enabled: root.overlayView !== "island"
            onClicked: {
                if (root.overlayView !== "island")
                    root.overlayView = "island"
            }

            // Pass through clicks to the widget box
            propagateComposedEvents: true
            z: -1
        }
    }

    IpcHandler {
        target: "theme-manager"
        // Re-read the live palette written by matugen (config.toml →
        // quickshell_theme template). Called by the system wallpaper pipeline
        // via the matugen post_hook, and acts as a reliable fallback in case
        // the file watcher misses matugen's atomic rewrite.
        function reload() {
            applyThemeColors(parseColors(themeFileWatcher.text()))
        }
    }

    IpcHandler {
        target: "main"

        function handleCommand(cmd: string, target: string, arg: string): void {
            if (cmd === "toggle") {
                if (root.overlayView === target)
                    root.overlayView = "island"
                else {
                    root.overlayView = target
                    Qt.callLater(() => widgetBox.forceActiveFocus())
                }
            } else if (cmd === "open") {
                root.overlayView = target
                Qt.callLater(() => widgetBox.forceActiveFocus())
            } else if (cmd === "close") {
                root.overlayView = "island"
            }
        }

        function toggleMovie() {
            handleCommand("toggle", "movies", "")
        }

        function toggleWallpaper() {
            handleCommand("toggle", "wallpaper", "")
        }

        // Event-driven brightness refresh. The keyboard brightness keybinds (and
        // the in-shell sliders) call this right after changing the backlight, so
        // the island updates instantly instead of waiting for HardwareMonitor's
        // poll loop.
        function refreshBrightness() {
            if (overlayRoot && overlayRoot.hwMonitor)
                overlayRoot.hwMonitor.refresh();
        }
    }

}
