import "./overlay"
import "./widgets"
import "./services"
import "./theme"
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland

ShellRoot {
    id: root

    property string overlayView: "island" // "island", "movie", "wallpaper"

    // Watch colors.json generated by matugen → push new values into Theme singleton
    FileView {
        id: themeFileWatcher
        path: Quickshell.shellPath("theme/colors.json")
        watchChanges: true
        onLoaded: applyColors()
        onTextChanged: applyColors()

        Component.onCompleted: {
            if (text().trim().length >= 10) applyColors();
        }

        function applyColors() {
            var t = text().trim()
            if (t.length < 10) return
            try {
                var c = JSON.parse(t)
                var batch = {}
                if (c.background) batch.background = c.background
                if (c.surface) batch.surface = c.surface
                if (c.surfaceBright) batch.surfaceBright = c.surfaceBright
                if (c.surfaceDim) batch.surfaceDim = c.surfaceDim
                if (c.surfaceContainer) batch.surfaceContainer = c.surfaceContainer
                if (c.surfaceVariant) batch.surfaceVariant = c.surfaceVariant
                if (c.primary) batch.primary = c.primary
                if (c.primaryFg) batch.primaryFg = c.primaryFg
                if (c.secondary) batch.secondary = c.secondary
                if (c.tertiary) batch.tertiary = c.tertiary
                if (c.backgroundFg) batch.backgroundFg = c.backgroundFg
                if (c.surfaceFg) batch.surfaceFg = c.surfaceFg
                if (c.surfaceVariantFg) batch.surfaceVariantFg = c.surfaceVariantFg
                if (c.outline) batch.outline = c.outline
                if (c.outlineVariant) batch.outlineVariant = c.outlineVariant
                if (c.error) batch.error = c.error
                for (var k in batch) Theme[k] = batch[k]
            } catch (e) {
                console.error("theme colors parse error:", e)
            }
        }
    }

    // Only one PanelWindow which manages the Island and all Overlays
    PanelWindow {
        id: mainWindow
        anchors { top: true; left: true; right: true }
        
        implicitHeight: Screen.height
        property bool needsLargeMask: overlayRoot.anyActive || root.overlayView !== "island"
        
        Timer {
            id: maskTimer
            interval: 400
            running: !overlayRoot.anyActive && root.overlayView === "island"
            onTriggered: mainWindow.needsLargeMask = false
        }
        
        Connections {
            target: overlayRoot
            function onAnyActiveChanged() {
                if (overlayRoot.anyActive) {
                    maskTimer.stop()
                    mainWindow.needsLargeMask = true
                } else {
                    maskTimer.restart()
                }
            }
        }
        
        mask: needsLargeMask ? fullMask : islandMask
        
        Region {
            id: fullMask
            Region { item: overlayRoot }
        }
        
        Region {
            id: islandMask
            Region { item: overlayRoot.island }
        }
        
        color: "transparent"
        WlrLayershell.exclusiveZone: 46
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.keyboardFocus: WlrKeyboardFocus.None

        OverlayRoot {
            id: overlayRoot
            anchors.fill: parent
            visible: root.overlayView === "island"
        }

        Loader {
            id: movieLoader
            anchors.fill: parent
            active: root.overlayView === "movie"
            source: root.overlayView === "movie" ? "movie.qml" : ""
            visible: active && root.overlayView === "movie"
            onItemChanged: {
                if (item) item.close.connect(function() { root.overlayView = "island" })
            }
        }

        Loader {
            id: wallpaperLoader
            anchors.fill: parent
            active: root.overlayView === "wallpaper"
            source: root.overlayView === "wallpaper" ? "wallpaper-picker.qml" : ""
            visible: active && root.overlayView === "wallpaper"
            onItemChanged: {
                if (item) item.close.connect(function() { root.overlayView = "island" })
            }
        }
    }

    IpcHandler {
        target: "main"

        function toggleMovie() {
            if (root.overlayView === "movie")
                root.overlayView = "island"
            else
                root.overlayView = "movie"
        }

        function toggleWallpaper() {
            if (root.overlayView === "wallpaper")
                root.overlayView = "island"
            else
                root.overlayView = "wallpaper"
        }
    }

}
