import "./overlay"
import "./widgets"
import "./services"
import "./theme"
import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland

ShellRoot {
    id: root

    property string overlayView: "island" // "island", "movies", "wallpaper"

    // Watch colors.json generated by matugen → push new values into Theme singleton
    FileView {
        id: themeFileWatcher
        path: Quickshell.shellPath("theme/colors.json")
        watchChanges: true
        onLoaded: applyColors()
        onTextChanged: applyColors()

        Component.onCompleted: {
            if (text().trim().length >= 10) applyColors();
        }

        function applyColors() {
            var t = text().trim()
            if (t.length < 10) return
            try {
                var c = JSON.parse(t)
                var batch = {}
                if (c.background) batch.background = c.background
                if (c.surface) batch.surface = c.surface
                if (c.surfaceBright) batch.surfaceBright = c.surfaceBright
                if (c.surfaceDim) batch.surfaceDim = c.surfaceDim
                if (c.surfaceContainer) batch.surfaceContainer = c.surfaceContainer
                if (c.surfaceVariant) batch.surfaceVariant = c.surfaceVariant
                if (c.primary) batch.primary = c.primary
                if (c.primaryFg) batch.primaryFg = c.primaryFg
                if (c.secondary) batch.secondary = c.secondary
                if (c.tertiary) batch.tertiary = c.tertiary
                if (c.backgroundFg) batch.backgroundFg = c.backgroundFg
                if (c.surfaceFg) batch.surfaceFg = c.surfaceFg
                if (c.surfaceVariantFg) batch.surfaceVariantFg = c.surfaceVariantFg
                if (c.outline) batch.outline = c.outline
                if (c.outlineVariant) batch.outlineVariant = c.outlineVariant
                if (c.error) batch.error = c.error
                for (var k in batch) Theme[k] = batch[k]
            } catch (e) {
                console.error("theme colors parse error:", e)
            }
        }
    }

    // Full-screen PanelWindow — like quickshellinspire, never resizes.
    // Island mode:  masked to island area, exclusive zone
    // Widget mode:  bounding box clips to widget, click-outside closes
    PanelWindow {
        id: mainWindow

        anchors { top: true; left: true; right: true }
        implicitHeight: Screen.height

        color: "transparent"
        WlrLayershell.namespace: "qs-shell"
        WlrLayershell.layer: WlrLayer.Overlay
        WlrLayershell.exclusiveZone: root.overlayView === "island" ? 46 : 0
        WlrLayershell.keyboardFocus: root.overlayView === "island" ? WlrKeyboardFocus.None : WlrKeyboardFocus.Auto

        focusable: true

        // ---------------------------------------------------------------
        // Mask — island area only in island mode, full screen otherwise
        // ---------------------------------------------------------------
        property bool needsLargeMask: overlayRoot.anyActive
        mask: root.overlayView === "island" ? (needsLargeMask ? fullMask : islandMask) : undefined

        Region {
            id: fullMask
            Region { item: overlayRoot }
        }

        Region {
            id: islandMask
            Region { item: overlayRoot.island }
        }

        Timer {
            id: maskTimer
            interval: 400
            running: !overlayRoot.anyActive && root.overlayView === "island"
            onTriggered: mainWindow.needsLargeMask = false
        }

        Connections {
            target: overlayRoot
            function onAnyActiveChanged() {
                if (overlayRoot.anyActive) {
                    maskTimer.stop()
                    mainWindow.needsLargeMask = true
                } else {
                    maskTimer.restart()
                }
            }
        }

        // ---------------------------------------------------------------
        // Island content — visible only in island mode
        // ---------------------------------------------------------------
        OverlayRoot {
            id: overlayRoot
            anchors.fill: parent
            visible: root.overlayView === "island"
        }

        // ---------------------------------------------------------------
        // Widget bounding box — like quickshellinspire's animated Item
        // Positions and clips to the widget's layout dimensions
        // ---------------------------------------------------------------
        Item {
            id: widgetBox
            visible: root.overlayView !== "island"
            focus: true

            // Layout dimensions per widget — matching quickshellinspire WindowRegistry.js
            readonly property bool isMovie: root.overlayView === "movies"
            readonly property int boxW: isMovie ? 1370 : Screen.width
            readonly property int boxH: isMovie ? 850 : 650
            readonly property int boxX: isMovie ? Math.floor((Screen.width / 2) - (boxW / 2)) : 0
            readonly property int boxY: isMovie ? Screen.height - boxH : Math.floor((Screen.height / 2) - (boxH / 2))

            x: boxX
            y: boxY
            width: boxW
            height: boxH
            clip: true

            Behavior on x { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }
            Behavior on y { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }
            Behavior on width { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }
            Behavior on height { NumberAnimation { duration: 230; easing.type: Easing.OutCubic } }

            opacity: visible ? 1.0 : 0.0
            Behavior on opacity {
                NumberAnimation { duration: 160; easing.type: visible ? Easing.OutCubic : Easing.InCubic }
            }

            Loader {
                id: movieLoader
                anchors.fill: parent
                active: root.overlayView === "movies"
                source: "movies/MovieWidget.qml"
                visible: active
                focus: active
            }

            Loader {
                id: wallpaperLoader
                anchors.fill: parent
                active: root.overlayView === "wallpaper"
                source: "wallpaper/WallpaperPicker.qml"
                visible: active
                focus: active
            }
        }

        // ---------------------------------------------------------------
        // Click-outside-to-close — full-screen MouseArea, like quickshellinspire
        // ---------------------------------------------------------------
        MouseArea {
            anchors.fill: parent
            enabled: root.overlayView !== "island"
            onClicked: {
                if (root.overlayView !== "island")
                    root.overlayView = "island"
            }

            // Pass through clicks to the widget box
            propagateComposedEvents: true
            z: -1
        }
    }

    IpcHandler {
        target: "main"

        function handleCommand(cmd, target, arg) {
            if (cmd === "toggle") {
                if (root.overlayView === target)
                    root.overlayView = "island"
                else {
                    root.overlayView = target
                    Qt.callLater(() => widgetBox.forceActiveFocus())
                }
            } else if (cmd === "open") {
                root.overlayView = target
                Qt.callLater(() => widgetBox.forceActiveFocus())
            } else if (cmd === "close") {
                root.overlayView = "island"
            }
        }

        function toggleMovie() {
            handleCommand("toggle", "movies", "")
        }

        function toggleWallpaper() {
            handleCommand("toggle", "wallpaper", "")
        }
    }

}
