import "../overlay"
import "../widgets"
import "../services"
import "../theme"
import QtQuick
import Quickshell
import Quickshell.Io

Item {
    id: root

    // Explicitly typed as 'color' for strict QML binding
    property color base: "#1e1e2e"
    property color mantle: "#181825"
    property color crust: "#11111b"
    property color text: "#cdd6f4"
    property color subtext0: "#a6adc8"
    property color subtext1: "#bac2de"
    property color surface0: "#313244"
    property color surface1: "#45475a"
    property color surface2: "#585b70"
    property color overlay0: "#6c7086"
    property color overlay1: "#7f849c"
    property color overlay2: "#9399b2"
    property color blue: "#89b4fa"
    property color sapphire: "#74c7ec"
    property color peach: "#fab387"
    property color green: "#a6e3a1"
    property color red: "#f38ba8"
    property color mauve: "#cba6f7"
    property color pink: "#f5c2e7"
    property color yellow: "#f9e2af"
    property color maroon: "#eba0ac"
    property color teal: "#94e2d5"

    property string rawJson: ""

    // Follow the shell's own theme source (theme/colors.json, generated by
    // matugen and watched by Theme.qml) instead of an external
    // quickshellinspire path. Keys are mapped from matugen's
    // names onto the Catppuccin-style names the movie/wallpaper
    // widgets expect, so the whole shell stays visually consistent.
    Process {
        id: themeReader
        command: ["cat", Quickshell.shellPath("theme/colors.json")]
        stdout: StdioCollector {
            onStreamFinished: {
                let txt = this.text.trim();
                if (txt !== "" && txt !== root.rawJson) {
                    root.rawJson = txt;
                    try {
                        let c = JSON.parse(txt);
                        if (c.background) root.base = c.background;
                        if (c.surfaceDim) root.mantle = c.surfaceDim;
                        if (c.surfaceContainer) root.crust = c.surfaceContainer;
                        if (c.backgroundFg) root.text = c.backgroundFg;
                        if (c.surfaceVariantFg) root.subtext0 = c.surfaceVariantFg;
                        if (c.surfaceFg) root.subtext1 = c.surfaceFg;
                        if (c.surfaceVariant) root.surface0 = c.surfaceVariant;
                        if (c.surfaceBright) root.surface1 = c.surfaceBright;
                        if (c.outlineVariant) root.surface2 = c.outlineVariant;
                        if (c.outline) root.overlay0 = c.outline;
                        if (c.outlineVariant) root.overlay1 = c.outlineVariant;
                        if (c.surfaceVariantFg) root.overlay2 = c.surfaceVariantFg;
                        if (c.secondary) root.blue = c.secondary;
                        if (c.secondary) root.sapphire = c.secondary;
                        if (c.tertiary) root.peach = c.tertiary;
                        if (c.tertiary) root.green = c.tertiary;
                        if (c.error) root.red = c.error;
                        if (c.primary) root.mauve = c.primary;
                        if (c.secondary) root.pink = c.secondary;
                        if (c.primary) root.yellow = c.primary;
                        if (c.error) root.maroon = c.error;
                        if (c.secondary) root.teal = c.secondary;
                    } catch(e) {}
                }
            }
        }
    }

    Timer {
        interval: 1000
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: themeReader.running = true
    }
}
